language: go
go:
  - 1.x
  - tip
os:
  - linux
before_install:
  - go get golang.org/x/lint/golint
  - go get -d ./...
script:
  - go build -tags=gofuzz ./...
  - go vet ./...
#  - golint -set_exit_status ./...
  - go test -v -tags=integration ./...
  - .travis/tests.sh
